### PR TITLE
No new print

### PR DESCRIPTION
**Pull request by ornicar**
improve parsing error messages, deprecate print matches

### CODE REVIEW

**Comment by thomas-daniels** [comment]
> deprecate Print matches

Is this what we want? (I may have missed a tavern discussion because I'll be mostly inactive until the 15th)

**Comment by ornicar** [comment]
https://lichess.org/mod/print/JptE8MlW

**Comment by thomas-daniels** [comment]
ahh cool! are you sure this isn't going to break on our existing config file that has plenty of them, because it's no longer in the enum? I can't immediately test myself

**Comment by ornicar** [comment]
I'll check it out. I only intend to disable new rules, not existing ones.

**Comment by ornicar** [comment]
It still is in the Enum https://github.com/ornicar/lichess-event-stream-watcher/blob/2f27fa11ee6f567e2b872e86f44eca6a0174fc1e/src/signup/rules.rs#L161-L163

**Pull request merged**
